spring:
  data:
    mongodb:
      host: 35.221.140.210
      port: 27017
      database: learn_query
      command:
        host: 35.221.140.210
        port: 27017
        database: learn_command
        username:
        password:
  redis:
    host: 35.221.140.210
server:
  port: 8081
#  ssl:
#    protocol: TLS
#    key-store: classpath:tomcat.keystore
#    key-store-password: 123456
#    key-store-type: JKS
#    key-alias: tomcat