spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: learn_query
      command:
        host: 127.0.0.1
        port: 27017
        database: learn_command
        username:
        password:
  profiles:
    active: local
server:
  port: 8443
  ssl:
    protocol: TLS
    key-store: classpath:tomcat.keystore
    key-store-password: 123456
    key-store-type: JKS
    key-alias: tomcat