spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: learn_query
      command:
        host: 127.0.0.1
        port: 27017
        database: learn_command
        username:
        password:
  profiles:
    active: local
logging:
  config: classpath:logback-${spring.profiles.active}.xml