spring:
  data:
    mongodb:
      host: 192.168.1.10
      port: 27017
      database: query_db
      username: query_db_user
      password: query_db_password
      command:
        host: 192.168.1.10
        port: 27017
        database: command_db
        username: command_db_user
        password: command_db_password
  redis:
    host: 192.168.1.10
    password: foo&`b0x7sQ8wfaredfoo&`b0x7sQ8wfaredfoo&`b0x7sQ8wfaredfoo&`b0x7sQ8wfared
server:
  port: 80