spring:
  data:
    mongodb:
      host: 34.92.5.133
      port: 27017
      database: query_db
      username: query_db_user
      password: query_db_password
      command:
        host: 34.92.5.133
        port: 27017
        database: command_db
        username: command_db_user
        password: command_db_password
  redis:
    host: 34.92.5.133
    password: foo&`b0x7sQ8wfaredfoo&`b0x7sQ8wfaredfoo&`b0x7sQ8wfaredfoo&`b0x7sQ8wfared
server:
  port: 80
#  ssl:
#    protocol: TLS
#    key-store: classpath:tomcat.keystore
#    key-store-password: 123456
#    key-store-type: JKS
#    key-alias: tomcat